let ng=0; const t=(n,c)=>{ if(!c) ng++; console.log(`  ${c?"✓":"✗"} ${n}`); };
console.log("=== スマホで設定 → サーバーへ ===");
customActions = normalizeTaskList(["提案書を作る","電話をする"]);
const id0 = customActions[0].id, id1 = customActions[1].id;
taskImportance[id0]="HIGH"; taskDue[id0]="2026-08-05"; taskEstimates[id0]=45;
const payload = toStored(["提案書を作る","電話をする"]);
t("重要度が載る", payload[0].imp==="HIGH");
t("期限が載る", payload[0].due==="2026-08-05");
t("想定時間が載る", payload[0].est===45);
t("設定していないタスクには付かない", payload[1].imp===undefined);
console.log("\n=== PCで受け取る（別端末を再現）===");
const received = normalizeTaskList(JSON.parse(JSON.stringify(payload)));
t("idが保たれる", received[0].id===id0 && received[1].id===id1);
t("重要度が届く", received[0].imp==="HIGH");
t("期限が届く", received[0].due==="2026-08-05");
t("想定時間が届く", received[0].est===45);
const takeIn=(cur,pick)=>{ const nx={...cur}; received.forEach(x=>{const v=pick(x);
  if(v===undefined||v===""||v===null) return; if(nx[x.id]!==undefined) return; nx[x.id]=v;}); return nx; };
t("PC側に重要度が入る", takeIn({},x=>x.imp)[id0]==="HIGH");
console.log("\n=== ★この端末で設定済みの値は上書きしない★ ===");
const pcHas={}; pcHas[id0]="LOW";
t("PCの LOW が守られる", takeIn(pcHas,x=>x.imp)[id0]==="LOW");
console.log("     （上書きすると「さっき変えたのに戻った」になる）");
console.log("\n=== 付随情報が無い旧データでも壊れない ===");
const legacy = normalizeTaskList(["古いタスク"]);
t("読める", legacy.length===1);
t("impは付かない", legacy[0].imp===undefined);
console.log(ng===0?"\n✓ 全て期待どおり":`\n✗ ${ng}件`);
process.exit(ng===0?0:1);
